// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Theme$ReactHooksTemplate = require("./Theme.bs.js");
var Generator$ReactHooksTemplate = require("./Generator.bs.js");

Css.$$global("body", /* :: */[
      Css.margin(Css.px(0)),
      /* :: */[
        Css.padding(Css.px(0)),
        /* :: */[
          Css.height(Css.vh(100)),
          /* [] */0
        ]
      ]
    ]);

Css.$$global("#app", /* :: */[
      Css.height(Css.pct(100)),
      /* [] */0
    ]);

var wrapper = Css.style(/* :: */[
      Css.height(Css.pct(100)),
      /* :: */[
        Css.display(Css.flexBox),
        /* :: */[
          Css.alignItems(Css.center),
          /* :: */[
            Css.justifyContent(Css.center),
            /* :: */[
              Css.fontFamily(Theme$ReactHooksTemplate.fontName),
              /* :: */[
                Css.backgroundColor(Css.hex("0E223B")),
                /* :: */[
                  Css.color(Css.hex("F8C50B")),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var header = Css.style(/* :: */[
      Css.fontSize(Css.rem(5)),
      /* [] */0
    ]);

var Styles = /* module */[
  /* wrapper */wrapper,
  /* header */header
];

function App(Props) {
  return React.createElement("div", {
              className: wrapper
            }, React.createElement("h1", {
                  className: header
                }, "0ZJ4SZ G0LDB3RG", React.createElement(Generator$ReactHooksTemplate.make, { })));
}

var make = App;

exports.Styles = Styles;
exports.make = make;
/*  Not a pure module */
