// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var db = /* array */[
  /* :: */[
    "Proszę zwrócić uwagę, że",
    /* :: */[
      "I tak mam trzy razy mniej czasu, proszę mi pozwolić powiedzieć:",
      /* [] */0
    ]
  ],
  /* :: */[
    "właściciele niewolników",
    /* :: */[
      "związkowcy",
      /* [] */0
    ]
  ],
  /* :: */[
    "po przeczytaniu \'Manifestu komunistycznego\'",
    /* :: */[
      "którymi się brzydzę",
      /* [] */0
    ]
  ],
  /* :: */[
    "udają homoseksualistów",
    /* :: */[
      "niszczą rodzinę",
      /* [] */0
    ]
  ],
  /* :: */[
    "żeby poddawać wszystkich tresurze",
    /* :: */[
      "bo taka jest ich natura",
      /* [] */0
    ]
  ],
  /* :: */[
    "co ma z resztą tyle samo sensu, co zawody w szachach dla debili",
    /* :: */[
      "co zostało dokładnie zaplanowane w Magdalence przez śp. generała Kiszczaka",
      /* [] */0
    ]
  ]
];

exports.db = db;
/* No side effect */
