// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Random = require("bs-platform/lib/js/random.js");
var $$String = require("bs-platform/lib/js/string.js");
var Database$ReactHooksTemplate = require("./Database.bs.js");

var quote = Css.style(/* :: */[
      Css.fontSize(Css.rem(1.5)),
      /* :: */[
        Css.maxWidth(Css.px(960)),
        /* :: */[
          Css.margin(Css.auto),
          /* :: */[
            Css.fontWeight(Css.light),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* quote */quote];

function randomFromList(list) {
  Random.init(Date.now() | 0);
  var index = Random.$$int(List.length(list));
  return List.nth(list, index);
}

function arrayToStringReducer(accumulator, element) {
  return $$String.concat(" ", /* :: */[
              accumulator,
              /* :: */[
                element,
                /* [] */0
              ]
            ]);
}

function generateSentence(db) {
  return $$Array.fold_left(arrayToStringReducer, "", $$Array.map(randomFromList, db));
}

function Generator(Props) {
  return React.createElement("div", {
              className: quote
            }, generateSentence(Database$ReactHooksTemplate.db));
}

var make = Generator;

exports.Styles = Styles;
exports.randomFromList = randomFromList;
exports.arrayToStringReducer = arrayToStringReducer;
exports.generateSentence = generateSentence;
exports.make = make;
/* quote Not a pure module */
